### ISSUE TITLE
error: port is missing traefik

### ISSUE THREAD

**Issue by atakoraworks** [Dokploy/examples#7]
Keep getting this error in the logs

```2024-11-21T04:50:06Z ERR error="service \"dokploy-traefik\" error: port is missing" container=dokploy-traefik-tsx91dk58lhakshq3kfokcmtk providerName=swarm```

This error keeps coming out in the traefik log monitoring

**Comment by Siumauricio** [comment]
Duplicate https://github.com/Dokploy/dokploy/issues/446
